apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: apache-helm-release
  namespace: flux-system
spec:
  # Reference to the HelmRepository containing the chart
  interval: 5m
  chart:
    spec:
      chart: apache
      version: 10.2.4
      sourceRef:
        kind: HelmRepository
        name: apache-helm-repo
        namespace: flux-system
      interval: 1m
  # Helm values to override
  values:
    namespace: dev
    replicaCount: 3
