apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBZDARaNd7zZTFHZfQ3gwvyF1kM5OE2kLhEmAznTADluv6QBouyyq1FBvEQUvlWCpxQL+lmsGCrgywJPye8fAPxvJTIs8LjavvXIE6Vzd5HnPwHL6NT4R9ASzNDshxfNaEcmSU7/uKRHIuqNEp8BdNp9J+xDkVIPztmAz4EkR+uGUx9lBM00Wwjg8jNlekH/cxxzDJc4Wcz1Kh9/j8cJun1GHMVyTJ0/zJVXD+zEiFDvB87DO1asEhSo8LwXKgpHKi8/P40ubLsnwuicH7rIrYijoxhPPLjGiEi0A3Z2G/h6KUrVkPushCAHroZAKPKvnIiY9xb7y1/IqfmoKWGc3czxAT4ZaTMU/PgShC1TvPDmeTjt7N8PIE9AO1XIOsNvEAcCqYjbiUdxl+4w55/l4IfX4JxuaxFWu7LZK5kAmfxPBwPtNu2eTrBY6/hE4s5VBLIyrNj+VVvkSEjHjmRiNR97bBjyIlOTzMnIBEX07xhMYxA067bAAnKivTN+74l9L2ilKfnIdAMYfYGEdFOCkwRxy4XaMPIlnmayOqpC9qIVSgvsuA2v/PoEFmcy58184/NQk2WcP1gSC5OYKZFrd7rF1Rd6N5rc1Z2eON+vwlSeH4qN8329HJKQU4sevR1+BYK0PlD5IduPCm1aoWI1NVEydMotM9lGOTxl9QnG9RYlXaImMuqc1BZzFszAB/4YCR2xF0W11oCBJ0=
    DB_USERNAME: AgBWAedyWyGItBrJlF8e7BpYX/qEDdMJSXD7UjNCS7P9XGeOFzWu3ZHjfKNGVW9wkuPhbTM7RmPHrVz3UOfPBEXBuoYeVTLBb5ZUZCfkpW/Wg2b7XfJ1IIeptEdjv8sJ454s9i3LczpB/Yo7MqrDEXRs1CPBQ0e7oLWJWfFLWRaY6g7MxYEk+IlMJ8HeiFpIgF4RIbgfwPuH+ntrwPh1EIzh5yhjlasMezA4LdapedLu6r5RxV/rjllS8rFEc62xby0tVJufax5TF3D3hKiDiDsmmdyJ8GCBY98TiPGVKgHJ/1e4i1ZKc+1/1ksUfVF2Xgiuk2rCpWN3ZfWqigCs1RdhzwKWxzj36Y0Ej1tsxgImqiNzG7LzFInYrJhuSdNuPcltE30Z5GANcWB0dJTGHce3wPa56qGQOEVFqVXYBkPLr1FEfjLdM66mKlHHdXEcZjYe50KwYQROnJD5TbD+fmxYDt247yZNzkd/fnAdW3W8w4pTN37eNJOHNbU/zW4oaQpI+RjKQCSaqIulQRxsXV9X9XUA1/r9NWit2t7SkA3vQAj87fu0DhdBTrXcW2Glqh2q0wXf6/en3N9rJzI9FE8hW9F4MGUhSabRlqK93TET1ziZMJ/jhgXHc373TPxtxLvAIZWWHDpR2mqVuS0DSQd+N66qXMjPXJXZCDRA5zauwYfZr0Gm8mD5QFrpzrI0DPNM2OC+1jEwgw==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
---
